{% set name = "spatialdata-io" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialdata_io-{{ version }}.tar.gz
  sha256: 36beeaf309a0edcedb8d9db41f5c8a894be2daee4f453c6844e6e35beec232ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - anndata
    - numpy
    - scanpy
    - spatialdata >=0.2.1
    - scikit-image
    - h5py
    - joblib
    - imagecodecs
    - dask-image
    - pyarrow
    - readfcs

test:
  imports:
    - spatialdata_io
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scverse/spatialdata-io
  summary: SpatialData IO for common techs
  dev_url: https://github.com/scverse/spatialdata-io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LucaMarconato
    - giovp
    - melonora
    - kevinyamauchi
