{% set name = "spatialdata-io" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatialdata_io-{{ version }}.tar.gz
  sha256: 212f884794274ce1cf6bed22f4060bdde119f551c63a15c4c5bcf09da1718837

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - anndata >=0.9.1
    - dask
    - dask-image
    - geopandas
    - h5py
    - imagecodecs
    - imageio
    - joblib
    - multiscale-spatial-image >=1.0.0
    - numpy
    - packaging
    - pandas
    - pyarrow
    - python >={{ python_min }}
    - pyyaml
    - readfcs
    - scanpy
    - scikit-image
    - scipy
    - shapely
    - spatial-image >=1.0.0
    - spatialdata >=0.2.2
    - tifffile
    - tqdm
    - xarray
    - zarr
test:
  imports:
    - spatialdata_io
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/spatialdata-io
  summary: SpatialData IO for common techs
  dev_url: https://github.com/scverse/spatialdata-io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LucaMarconato
    - giovp
    - melonora
    - kevinyamauchi
